### ISSUE TITLE
Easier way to pin to Start?

### ISSUE THREAD

**Issue by Susko3** [claire-west/util-scripts#1]
The method described in [`cmd/README.md`](https://github.com/claire-west/util-scripts/blob/bc73e1c83060d0b7b9194680053a509ca09844c9/cmd/README.md) seems overly complicated.

Creating a shortcut to the script in `%AppData%\Microsoft\Windows\Start Menu\Programs` and then pinning the script from the start menu search directly seems much easier and less prone to errors (unless that doesn't work on Windows 11).
Could also put all the scripts neatly in a folder (eg. `Start Menu\Programs\Scripts`) that way.

**Comment by cv4x** [comment]
Oh wow that is extremely silly... you can't pin when right clicking the file (or shortcut) unless it's an exe, but if you search for the file and then right click it in the search results then the option is available.
